### ISSUE TITLE
GitHub Topics are missing

### ISSUE THREAD

**Issue by elharony** [MOhammedRiaad/React-Interview-Questions#2]
There's no GitHub Topics for the repo. Try to add relevant topics by clicking on `Manage Topics`, and use something like `interview-questions` and similar topics.

By adding relevant topics, the repo will get visible on GitHub Search, and - hopefully - will attract more developers to follow it! 👍

**Comment by MOhammedRiaad** [comment]
thank you for your suggestions , now topics are added successfully
